# Generated by Django 6.1 on 2026-08-21 06:05

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/menu_items/', validators=[core.validators.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='cover_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurants/covers/', validators=[core.validators.validate_image_size]),
        ),
    ]
