services:
  - type: web
    name: chay-review
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt && python manage.py collectstatic --noinput && python manage.py migrate && (python manage.py createsuperuser --noinput || true) && (if [ \"$SEED_OSM_DATA\" = \"1\" ]; then python manage.py import_osm_restaurants; fi || true)"
    startCommand: "gunicorn core.wsgi"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: ".onrender.com"
      - key: DATABASE_URL
        sync: false
      - key: USE_CLOUDINARY
        value: "True"
      - key: CLOUDINARY_URL
        sync: false
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: SEED_OSM_DATA
        value: "0"
