# Generated by Django 6.1 on 2026-08-21 06:05

import core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(upload_to='reviews/photos/', validators=[core.validators.validate_image_size]),
        ),
    ]
